### ISSUE TITLE
Convert GraphData from/to NetworkX with features

### ISSUE THREAD

**Issue by TristanBilot** [mlx-graphs/mlx-graphs#110]
### Step 1
`from_networkx` has been implemented in https://github.com/mlx-graphs/mlx-graphs/pull/109, but it lacks the cases where attributes/features exist in the `GraphData`.

One may want to follow the same methodology as in [PyG](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/utils/convert.html#from_networkx).

### Step 2
The same applies for `to_networkx`. This function is not yet implemented.

**Comment by Kheims** [comment]
I can handle this but not until end of week as i am fully dedicated to neighbor sampler as of now

**Comment by TristanBilot** [comment]
It's ok, neighbor sampling is more important 😅. Anyone interested can go with this issue.

**Comment by francescofarina** [comment]
Completed by @vinayhpandya in #154.
