### ISSUE TITLE
Add some util methods to GraphData

### ISSUE THREAD

**Issue by TristanBilot** [mlx-graphs/mlx-graphs#114]
We would enjoy to run some graph util methods directly from the `GraphData` object.

**Ex:**
```python
g = GraphData(...)
>>> g.is_undirected()
>>> g.is_directed()
>>> g.has_self_loops()
>>> g.has_isolated_nodes()
```

Some of these functions are already implemented in mlx-graphs and can be simply called, like `is_undirected` and `is_directed`. Others need to be implemented.

**Comment by francescofarina** [comment]
`has_self_loops` and `has_isolated_nodes` implemented in #159
