### ISSUE TITLE
Change in GCNConv normalization 

### ISSUE THREAD

**Issue by Kheims** [mlx-graphs/mlx-graphs#117]
As soon as we upgrade to mlx v0.5.0 we can change the [GCNConv normalization step](https://github.com/mlx-graphs/mlx-graphs/blob/main/mlx_graphs/utils/scatter.py#L199-L219), as `mx.where` now properly handles `inf` [see](https://github.com/ml-explore/mlx/releases/tag/v0.5.0)

**Comment by francescofarina** [comment]
V0.5 just came out
