### ISSUE TITLE
installation for benchmark on M3

### ISSUE THREAD

**Issue by thegodone** [mlx-graphs/mlx-graphs#119]
I have a M3 max 16 cpu - 40 GPU - 128 GB and want to add my contribution to the project:

but trying to install the dependencies, and run the benchmark code and I still have an issue with the pyg.
```
python launcher.py                                     
/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/torch_geometric/typing.py:54: UserWarning: An issue occurred while importing 'pyg-lib'. Disabling its usage. Stacktrace: dlopen(/Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/libpyg.so, 0x0006): Symbol not found: __ZN2at4_ops11randint_low4callExxN3c108ArrayRefIxEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEE
  Referenced from: <655519E1-C70C-3E43-AE6C-47B8454A9C72> /Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/libpyg.so
  Expected in:     <3B52B8C1-6D8D-3579-9E78-5C434F6331FD> /Users/tgg/miniforge3/envs/tf/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib
  warnings.warn(f"An issue occurred while importing 'pyg-lib'. "
zsh: segmentation fault  python launcher.py
```

can you provide a requirement.txt file to get the exact same env ?

best

**Comment by francescofarina** [comment]
Hi @thegodone, thanks for reporting that.

I just tried locally, creating a new environment from scratch, but can't reproduce that. Have you installed the benchmark dependencies (`pip install '.[benchmarks]'`)?

If you already did that, I see you're using miniforge - I think both @TristanBilot and I are working with venv. Is anyone else using it? Perhaps @Kheims?

**Comment by thegodone** [comment]
I think this is my setup that is not ideal. 

So that would be nice to have a clean dependencies requirement to be aligned.

**Comment by francescofarina** [comment]
I see - so, we're specifying requirements in the `pyproject.toml` ([here](https://github.com/mlx-graphs/mlx-graphs/blob/main/pyproject.toml)). 

Assuming you're in the root of the cloned repository, non-default/optional dependencies can be installed via `pip install '.[<dependency-group-name>]'` - for example to install the requirements needed to run benchmarks you can run `pip install '.[benchmarks]'`. More info [here](https://mlx-graphs.github.io/mlx-graphs/install.html#installing-test-dev-benchmarks-docs-dependencies).

If that creates issues with your environment we can explore it further. As a temporary workaround, all the requirements we currently have are
```
ipython==8.21.0
mlx==0.4.0
nbsphinx==0.9.3
numpy==1.26.3
pre-commit==3.6.0
pytest==7.4.4
requests==2.31.0
scipy==1.12.0
sphinx==7.2.6
sphinx-autodoc-typehints==1.25.2
sphinx-book-theme==1.1.0
sphinx-gallery==0.15.0
torch==2.2.0
torch_geometric==2.5.0
tqdm==4.66.1
```
You can potentially put them in a `requirements.txt` and install them.

**Comment by thegodone** [comment]
Just one more question , is pyg  "cpu" or "gpu" in arm64 ?

**Comment by francescofarina** [comment]
I'm not sure PyG/`torch_geometric` has two different versions (https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html)

**Comment by francescofarina** [comment]
@thegodone I just noticed that PyG is not available on Conda for M processors (see [here](https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html)), so you may need to move to pip to run the benchmarks.

**Comment by thegodone** [comment]
[M3Max_12P_4E_40GPU_128G.md](https://github.com/mlx-graphs/mlx-graphs/files/14462758/M3Max_12P_4E_40GPU_128G.md)

**Comment by francescofarina** [comment]
Those are some pretty great results @thegodone! I'll add them to a PR I'm working on with some refactoring

**Comment by francescofarina** [comment]
Added in #120 - thanks @thegodone! Feel free to run also the `training_loop` benchmarks if you get the chance and open a PR to add them ;)

**Comment by thegodone** [comment]
I don't see the dgl dependency in the pyproject.toml file

**Comment by francescofarina** [comment]
You're right, great catch 💯  I'll add it.
