### ISSUE TITLE
Importer/converter of OGB datasets

### ISSUE THREAD

**Issue by francescofarina** [mlx-graphs/mlx-graphs#127]
See https://ogb.stanford.edu/docs/dataset_overview/. We should be able to use the library-agnostic datasets and convert them to the mlx-graphs format.

**Comment by thegodone** [comment]
This is nice for existing datasets but not for private or new datasets. I make a issue for an example from scratch without OGB module.

**Comment by francescofarina** [comment]
Yes, this one will likely be a core dataset of `mlx-graphs` as it contains many benchmarks. We'll work on improving the tutorial on how to create custom datasets.
