### ISSUE TITLE
ESOL dataset using directly RDkit descriptors

### ISSUE THREAD

**Issue by thegodone** [mlx-graphs/mlx-graphs#128]
Can you provide an example from scratch off to convert Molecules objects into Atom / Nodes and Bond / Edge features for ESOL dataset ?

[ ] using RDkit
[ ] for GIN / GINE / DMPNN (chemProp) / AttentiveFP

**Comment by francescofarina** [comment]
@thegodone we currently have a basic example of how to build custom datasets [here](https://mlx-graphs.github.io/mlx-graphs/tutorials/quickstart.html).

Having a specific tutorial on how to use RDKit to convert the ESOL dataset and testing it with different architectures is definitely interesting but I think it's probably better suited to live outside of the main `mlx-graphs` repository, perhaps as a tutorial or a standalone project.

**Comment by francescofarina** [comment]
It would be great to have the ESOL dataset built within the library and we may as well do that over the coming weeks (or feel free to contribute to it 😉) but I think your question was more around showing how to make the conversion.

**Comment by thegodone** [comment]
I add this PR to make a demo on how to integrate a molecular dataset from scratch using rdkit and loading a file containing smiles and a target. I still have an issue cause the batch and the default dataset informations are not available (python errors)
