### ISSUE TITLE
qm9 example

### ISSUE THREAD

**Issue by thegodone** [mlx-graphs/mlx-graphs#132]
I modify the code to use leaky_relu activation and a max pooling this is my results:

![image](https://github.com/mlx-graphs/mlx-graphs/assets/1186658/d41400ec-41be-4c8c-b6fe-6f041cd94fb6)

**Comment by thegodone** [comment]
I made a PR

**Comment by francescofarina** [comment]
@thegodone was there an issue with the previous implementation?

**Comment by thegodone** [comment]
no just improve it.

Le mar. 5 mars 2024 à 16:09, Francesco Farina ***@***.***> a
écrit :

**Comment by thegodone** [comment]
sure, I was testing the other lmx features like leaky_relu and max pooling. Normally we get faster convergence 10 epochs versus 20 now. this means shorter to run demos etc...

**Comment by francescofarina** [comment]
@thegodone closing this - as @TristanBilot said, a standalone tutorial focused on performance would be absolutely welcome!
