### ISSUE TITLE
What are the incoming graphs that will be implemented ?

### ISSUE THREAD

**Issue by thegodone** [mlx-graphs/mlx-graphs#138]
Do you think you can list some graphs that could be cool to add here as a task ?

**Comment by francescofarina** [comment]
@thegodone just to be sure to answer your question: what do you mean by graphs to add? If you're referring to features to add to `mlx-graphs` we're tracking them through the issues.

**Comment by thegodone** [comment]
I mean convolutions methods like attentiveFP or GATv2 for example

**Comment by francescofarina** [comment]
Ah, ok - I think basic layers should be the priority (for example we currently lack basic aggregation and normalization layers). On convolutions specifically, GATv2 could be a good candidate.
