### ISSUE TITLE
Improve edge_weigths description in GINConv

### ISSUE THREAD

**Issue by thegodone** [mlx-graphs/mlx-graphs#141]
Is the edge_weigths are a way to do GINE ? this is not clear in the arg definition:             edge_weights: Edge weights leveraged in message passing. Default: ``None``

Normally, we need to do first a linear projection of edge_features into node_features for GINE code (https://github.com/akensert/molgraph/blob/main/molgraph/layers/convolutional/gin_conv.py or https://github.com/aimat-lab/gcnn_keras/blob/master/kgcnn/literature/GIN/_model.py)

**Comment by TristanBilot** [comment]
So basically, the `edge_weights` arg can be passed to any `MessagePassing` layer. They will just weigh the features from neighbors in the `message` function. `edge_weights` is supposed to store scalar elements for each edge, so it has a shape (E, ) or (E, 1).
Edge features are thus not implemented yet in GIN. To integrate GINE, we may want to create a dedicated `GINE` layer that applies the projection on the edge features beforehand.

**Comment by thegodone** [comment]
Generally this is the second option that makes more sense cause it's just an extension of the GIN.

**Comment by TristanBilot** [comment]
Would you like to work on this issue @thegodone?

**Comment by thegodone** [comment]
I will but not this week

Le jeu. 7 mars 2024 à 21:30, Tristan Bilot ***@***.***> a
écrit :
