### ISSUE TITLE
Add fixture to remove files created during testing

### ISSUE THREAD

**Issue by francescofarina** [mlx-graphs/mlx-graphs#148]
**Is your feature request related to a problem? Please describe.**

We're currently explicitly deleting files created during tests in the tests themselves. We need to automate that.

**Describe the solution you'd like**

We can use a Pytest fixture.

**Describe alternatives you've considered**

None

**Additional context**
None

**Comment by vinayhpandya** [comment]
Will the tmp_path fixture work? we don't need to add any extra code or create our own fixtures

**Comment by francescofarina** [comment]
Yes, the built in tmp_path fixture may do the job! I haven't looked into the details yes though.
