### ISSUE TITLE
Add notebooks/markdown examples in docs for node/edge/graph classification

### ISSUE THREAD

**Issue by TristanBilot** [mlx-graphs/mlx-graphs#30]
Examples with explanations of how using `mlx-graphs` for real scenarios with known datasets would be nice.
[Ex](https://pytorch-geometric.readthedocs.io/en/latest/get_started/colabs.html) in PyG.

**Comment by francescofarina** [comment]
100%. Let's do this immediately after we have the batching/dataloaders in place so that we can import a few datasets?

**Comment by TristanBilot** [comment]
Yep exactly!

**Comment by TristanBilot** [comment]
We shall also add few examples of how converting PyG and DGL code to equivalent in mlx-graphs. It's gonna be useful for users beginner with MLX.

**Comment by francescofarina** [comment]
We can also add some aux functions to import data or convert stuff from PyG

**Comment by TristanBilot** [comment]
Some examples:
* [DGL tutorials](https://docs.dgl.ai/tutorials/blitz/index.html)
* [DGL link prediction tutorial](https://docs.dgl.ai/tutorials/blitz/4_link_predict.html#sphx-glr-tutorials-blitz-4-link-predict-py)
* [DGL GCN notebook](https://github.com/dmlc/dgl/blob/fe78093fb74719e39e4bba372d44822a4be8c568/notebooks/sparse/gcn.ipynb#L26)
* [DGL quickstart notebook](https://github.com/dmlc/dgl/blob/fe78093fb74719e39e4bba372d44822a4be8c568/notebooks/sparse/quickstart.ipynb)
* [DGL with sparse matrices](https://github.com/dmlc/dgl/blob/fe78093fb74719e39e4bba372d44822a4be8c568/notebooks/sparse/gcn.ipynb#L26)
*
