### ISSUE TITLE
Neighbor sampler

### ISSUE THREAD

**Issue by TristanBilot** [mlx-graphs/mlx-graphs#47]
Like the one in GraphSAGE and [PyG](https://github.com/pyg-team/pytorch_geometric/blob/51c57da51d45c19497d393cc678c215eb341b3b4/torch_geometric/sampler/neighbor_sampler.py#L34). However, I think this will require C++ if we want an efficient sampling (all frameworks have a cpp implementation for this operation).

**Comment by francescofarina** [comment]
Are you thinking of having that implemented in `mlx` or in `mlx-graphs`?

**Comment by TristanBilot** [comment]
Moved to https://github.com/mlx-graphs/mlx-graphs/issues/94 as we'll first start with a Python implementation.
