### ISSUE TITLE
Remove/add self loops extremely slow

### ISSUE THREAD

**Issue by TristanBilot** [mlx-graphs/mlx-graphs#86]
This function is so slow that we can't use it in practice, maybe we can take inspiration from [PyG](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/utils/loop.html#remove_self_loops).

To reproduce:
```python
import mlx.core as mx
from mlx_graphs.utils import remove_self_loops

edge_index = mx.ones((2, 1_000_000))
remove_self_loops(edge_index)
```

I ran this 3min ago and it's still running 😅

I also get this once it's finished: ValueError: [gather] Got indices with invalid dtype. Indices must be integral.

**Comment by francescofarina** [comment]
See #87.

If you run

```
import timeit

import mlx.core as mx

from mlx_graphs.utils import remove_self_loops

edge_index_1 = mx.ones((2, 1_000_000))
edge_index_2 = mx.array([[0, 0, 1, 1], [0, 1, 0, 2]])
edge_index = mx.concatenate([edge_index_1, edge_index_2], 1)

times = timeit.Timer(lambda: remove_self_loops(edge_index)).repeat(repeat=10, number=1)

print(min(times))
```

you should see it's now much faster
