### ISSUE TITLE
Save processed datasets

### ISSUE THREAD

**Issue by francescofarina** [mlx-graphs/mlx-graphs#96]
Datasets are currently re-processed every time as mlx arrays cannot be pickled currently.

**Comment by Dsantra92** [comment]
Would love to take it up.

**Comment by TristanBilot** [comment]
Thanks for taking this issue @Dsantra92! We currently struggle to save the datasets to disk as the MLX arrays are not pickle-able yet. 
Someone seems to plan working on it though: https://github.com/ml-explore/mlx/issues/367

If you want to implement this feature without pickle you can use [savez](https://ml-explore.github.io/mlx/build/html/python/_autosummary/mlx.core.savez.html) to store multiple arrays into a file on disk. However this require to rebuild a Dataset object from the lists of arrays. 

This is not the cleanest solution but it could do the job while waiting to store directly the Dataset object to disk with pickle-able arrays.

**Comment by francescofarina** [comment]
There's currently an open PR on mlx https://github.com/ml-explore/mlx/pull/713

**Comment by TristanBilot** [comment]
Perfect!

**Comment by TristanBilot** [comment]
Pickle is now implemented in MLX 🚀
https://github.com/ml-explore/mlx/pull/713
We can now save datasets on disk.
